name: disawar_king_app
description: "Disawar King Official App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

flutter:
  uses-material-design: true
